name: SNOWFLAKE_GIT_INTEGRATION

on:
  push:
    branches:
      - main
  
jobs:
  deploy-snowflake-job:
    runs-on: ubuntu-latest

    env:
      SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASS }}
      SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACC }}
      SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWSQL_DATABASE: ${{ secrets.SNOWFLAKE_DB }}
      SNOWSQL_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SnowSQL
        uses: snowflakedb/snowflake-actions/setup-cli@master
        with:
          version: 'latest'
      
      - name: Fetch files from github repo
        run: |
          snowsql -u $SNOWSQL_USER \
                -a $SNOWSQL_ACCOUNT \
                -d $SNOWSQL_DATABASE \
                -s $SNOWSQL_SCHEMA \
                -q "SELECT 1;"
